/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

#define POWER_CLOCK_IRQHandler power_clock_isr
#define RADIO_IRQHandler radio_isr
#define UARTE0_UART0_IRQHandler uarte0_uart0_isr
#define SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler spim0_spis0_twim0_twis0_spi0_twi0_isr
#define SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler spim1_spis1_twim1_twis1_spi1_twi1_isr
#define NFCT_IRQHandler nfct_isr
#define GPIOTE_IRQHandler gpiote_isr
#define SAADC_IRQHandler saadc_isr
#define TIMER0_IRQHandler timer0_isr
#define TIMER1_IRQHandler timer1_isr
#define TIMER2_IRQHandler timer2_isr
#define RTC0_IRQHandler rtc0_isr
#define TEMP_IRQHandler temp_isr
#define RNG_IRQHandler rng_isr
#define ECB_IRQHandler ecb_isr
#define CCM_AAR_IRQHandler ccm_aar_isr
#define WDT_IRQHandler wdt_isr
#define RTC1_IRQHandler rtc1_isr
#define QDEC_IRQHandler qdec_isr
#define COMP_LPCOMP_IRQHandler comp_lpcomp_isr
#define SWI0_EGU0_IRQHandler swi0_egu0_isr
#define SWI1_EGU1_IRQHandler swi1_egu1_isr
#define SWI2_EGU2_IRQHandler swi2_egu2_isr
#define SWI3_EGU3_IRQHandler swi3_egu3_isr
#define SWI4_EGU4_IRQHandler swi4_egu4_isr
#define SWI5_EGU5_IRQHandler swi5_egu5_isr
#define TIMER3_IRQHandler timer3_isr
#define TIMER4_IRQHandler timer4_isr
#define PWM0_IRQHandler pwm0_isr
#define PDM_IRQHandler pdm_isr
#define MWU_IRQHandler mwu_isr
#define PWM1_IRQHandler pwm1_isr
#define PWM2_IRQHandler pwm2_isr
#define SPIM2_SPIS2_SPI2_IRQHandler spim2_spis2_spi2_isr
#define RTC2_IRQHandler rtc2_isr
#define I2S_IRQHandler i2s_isr
#define FPU_IRQHandler fpu_isr
