/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script from ./include/libopencm3/nrf5/2/irq.json
 */

#ifndef LIBOPENCM3_NRF5_2_NVIC_H
#define LIBOPENCM3_NRF5_2_NVIC_H

#include <libopencm3/cm3/nvic.h>

/** @defgroup CM3_nvic_defines_NRF52 User interrupts for NRF5 2 series
    @ingroup CM3_nvic_defines

    @{*/

#define NVIC_POWER_CLOCK_IRQ 0
#define NVIC_RADIO_IRQ 1
#define NVIC_UARTE0_UART0_IRQ 2
#define NVIC_SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQ 3
#define NVIC_SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQ 4
#define NVIC_NFCT_IRQ 5
#define NVIC_GPIOTE_IRQ 6
#define NVIC_SAADC_IRQ 7
#define NVIC_TIMER0_IRQ 8
#define NVIC_TIMER1_IRQ 9
#define NVIC_TIMER2_IRQ 10
#define NVIC_RTC0_IRQ 11
#define NVIC_TEMP_IRQ 12
#define NVIC_RNG_IRQ 13
#define NVIC_ECB_IRQ 14
#define NVIC_CCM_AAR_IRQ 15
#define NVIC_WDT_IRQ 16
#define NVIC_RTC1_IRQ 17
#define NVIC_QDEC_IRQ 18
#define NVIC_COMP_LPCOMP_IRQ 19
#define NVIC_SWI0_EGU0_IRQ 20
#define NVIC_SWI1_EGU1_IRQ 21
#define NVIC_SWI2_EGU2_IRQ 22
#define NVIC_SWI3_EGU3_IRQ 23
#define NVIC_SWI4_EGU4_IRQ 24
#define NVIC_SWI5_EGU5_IRQ 25
#define NVIC_TIMER3_IRQ 26
#define NVIC_TIMER4_IRQ 27
#define NVIC_PWM0_IRQ 28
#define NVIC_PDM_IRQ 29
#define NVIC_MWU_IRQ 30
#define NVIC_PWM1_IRQ 31
#define NVIC_PWM2_IRQ 32
#define NVIC_SPIM2_SPIS2_SPI2_IRQ 33
#define NVIC_RTC2_IRQ 34
#define NVIC_I2S_IRQ 35
#define NVIC_FPU_IRQ 36

#define NVIC_IRQ_COUNT 37

/**@}*/

/** @defgroup CM3_nvic_isrprototypes_NRF52 User interrupt service routines (ISR) prototypes for NRF5 2 series
    @ingroup CM3_nvic_isrprototypes

    @{*/

BEGIN_DECLS

void power_clock_isr(void);
void radio_isr(void);
void uarte0_uart0_isr(void);
void spim0_spis0_twim0_twis0_spi0_twi0_isr(void);
void spim1_spis1_twim1_twis1_spi1_twi1_isr(void);
void nfct_isr(void);
void gpiote_isr(void);
void saadc_isr(void);
void timer0_isr(void);
void timer1_isr(void);
void timer2_isr(void);
void rtc0_isr(void);
void temp_isr(void);
void rng_isr(void);
void ecb_isr(void);
void ccm_aar_isr(void);
void wdt_isr(void);
void rtc1_isr(void);
void qdec_isr(void);
void comp_lpcomp_isr(void);
void swi0_egu0_isr(void);
void swi1_egu1_isr(void);
void swi2_egu2_isr(void);
void swi3_egu3_isr(void);
void swi4_egu4_isr(void);
void swi5_egu5_isr(void);
void timer3_isr(void);
void timer4_isr(void);
void pwm0_isr(void);
void pdm_isr(void);
void mwu_isr(void);
void pwm1_isr(void);
void pwm2_isr(void);
void spim2_spis2_spi2_isr(void);
void rtc2_isr(void);
void i2s_isr(void);
void fpu_isr(void);

END_DECLS

/**@}*/

#endif /* LIBOPENCM3_NRF5_2_NVIC_H */
